### ISSUE TITLE
Unexpected behavior when trying to upload image with a name that already exists, in rise-image settings

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-vision-apps#1061]
If I open the image editor, if I try to upload an image with the same name of one that already exists, it does not upload it ( fails silently ), but instead it adds the original image thumbnail multiple times to the list:

![duplicated](https://user-images.githubusercontent.com/33162690/59878665-7b8c7900-936e-11e9-8ff0-1cc20744df9f.png)

**Comment by santiagonoguez** [comment]
May be related to 
https://github.com/Rise-Vision/rise-vision-apps/issues/1076

that reports similar behavior, but when selecting from storage.

**Comment by fjvallarino** [comment]
@sheadarlison I wanted to validate what your expectation here is. Uploading the same image multiple times results in the same image being repeated in the list. This is a similar (the same?) behavior as in issue #1076, which was closed because the behavior was the expected. Changing this is not complex, but I just want to be sure if we want to change it. Thanks!

@stulees FYI

**Comment by sheadarlison** [comment]
Issue #1076 was a bit different, the user was adding the same image from storage multiple times, not uploading. 

@fjvallarino if a user is uploading an image with the same filename the existing file should be ovewritten and a second file should NOT be added to the list. It seems like Storage silently fails here and in the storage app instead of overwriting. 

Let me know if that makes sense.

FYI @ezequielc this is the why behind my question in the conversion room.

**Comment by fjvallarino** [comment]
@santiagonoguez is it ok to close this issue now?

**Comment by santiagonoguez** [comment]
@fjvallarino go ahead, thanks !

**Comment by fjvallarino** [comment]
@santiagonoguez @sheadarlison @stulees this has been deployed and validated in Production
