### ISSUE TITLE
[Image Component] Warped Preview Image

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1160]
**Defect:** When uploading an image using the Image Component, the preview image here appears a bit squashed/warped horizontally:

![image21](https://user-images.githubusercontent.com/1440943/62785903-28d66000-ba87-11e9-9566-a46e30c95a70.jpg)

**Comment by willread** [comment]
@jasoncaldwell Since the rows are a fixed height, we'll have some extra space around the images when they're not the exact right aspect ratio, here's a quick example of what it would look like:

![image](https://user-images.githubusercontent.com/768495/63971446-b3492880-ca63-11e9-9dd4-7f5ba53a746e.png)

I also added a border radius which was in the style guide but missing.

Does this look good to you?

**Comment by jasoncaldwell** [comment]
@willread Looks good! Ultimately, I think it would be cool to crop the images to "fit" inside of the container. But for now, it's good.

**Comment by willread** [comment]
@jasoncaldwell This has been pushed to apps.risevision.com, please validate and let me know when I can close this.

**Comment by jasoncaldwell** [comment]
@willread Looks good! You can close.
