### ISSUE TITLE
Non System Administrators get a strange error message when trying to update Company information

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1181]
### What is the expected behavior?
When a non System Administrator user accesses the Company Settings, they should be notified they cannot change any information on this page since they don't have the user rights.

### What is the actual behavior?
When the non System Administrator tries data on this page, specifically the time zone, they get  errors like this:
![2019-08-14_7-19-29](https://user-images.githubusercontent.com/6862256/63017306-ff8d4980-be63-11e9-9630-408b5944e3e0.png)

### What steps can be taken to replicate the problem?
Log in as a non System Administrator, go to the Company Settings, try to change the timezone.

**Comment by ezequielc** [comment]
@sheadarlison Non System Administrators should not be able to edit Company Settings. The links to open it are hidden when they don't have permission, but Billing page has a link that is not getting hidden (to edit Billing Notification Emails). 
My suggestion for the fix is to hide that link for non System Administrator. Let me know if you agree. Thanks!

**Comment by sheadarlison** [comment]
@ezequielc agreed. Thanks

**Comment by ezequielc** [comment]
In addition to the billing page, there was also a link from Weather Attributes Editor. Fixed both to not be listed to users without proper permission. Thanks
