### ISSUE TITLE
Storage App shows "Your trial has expired"

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#1224]
**Steps to recreate**

1. Go to a Company that has an expired trial, but is a sub-company of another organization sharing a licensing subscription.
2. Go to the [storage app in that sub-company](https://apps.risevision.com/storage?cid=68cf2037-b482-4e58-8747-eb83662f39e1).

**What happens?**
You see the error message [Your trial has expired Subscribe Now](https://www.screencast.com/t/O09Ug50IkHc).

Licensed Displays showing storage content show "Rise Storage Subscription not active".

**What should happen?**
Sub-companies that inherit a parent company's Display Licenses and have an expired trial should not see this error message. Licensed Displays should show storage content.

**Comment by olegrise** [comment]
I'm going to close this issue. The problem was on the data side and it was corrected by @alex-deaconu. I didn't find any problem with the code. 

The reason why Product Status API is used there and not Authorization API is because Authorization API requires Display ID.

Re. "Expired Trial takes precedence over the Cancelled Subscription" - it doesn't really matter if Product Status API returns "subscription was cancelled" or "Trial Expired" because both mean that there is no active subscription/trial. Changing the code to return "subscription was cancelled" status in this case will just make code more complex without obvious benefit.

**Comment by alex-deaconu** [comment]
@olegrise makes sense, thanks for the clarifications!
