### ISSUE TITLE
Pop Quiz Template not displaying properly + issue in the schedule

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/rise-vision-apps#1304]
### What is the expected behavior?
- The template loads and cycles through trivia questions.

### What is the actual behavior?
-After adding their logo to the template, the content disappeared from the preview.  Also, when scheduled the template would always appear first in the playlist and wouldn't advance past to the next presentation on the list.

### What steps can be taken to replicate the problem?
- I was unable to replicate.

**Comment by ezequielc** [comment]
@pcsandford @mmeiers fyi, I think you should grab this. Thanks!

**Comment by mmeiers** [comment]
@jrkuchta The reason it was getting stuck was due to a defect that was resolved today. I verified it will move to the next template in a schedule now.
https://github.com/Rise-Vision/html-template-library/issues/592

There are two ways you can apply a logo to this template. In the "branding settings" or the template specific settings "Image - Logo" https://www.screencast.com/t/uGTiPHxYxe6. If the "Image - Logo" is empty their branding logo will not show. This is by design so a user has a way to override brand settings or choose to not have a logo. If they want the logo from branding to show back up they can re-add the template. 

If this is not what they are seeing please ask for clarification or a link to the template in question so we can take a look.
