### ISSUE TITLE
Classic Editor can't access Rise Storage

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1356]
### What is the expected behavior?
Can select images and videos stored in Rise Storage when building content in Classic Editor.
### What is the actual behavior?
Storage is blank when accessed from Classic Editor.  I can verify it works as expected from Editor and Templates Editor.
### What steps can be taken to replicate the problem?
1. go to rva.risevision.com
2. create a new presentation
3. create a placeholder
4. right-click it, choose properties
5. add content, add an image item
6. click "configure"
7. choose "single image"

here's a quick video overview just in case that's too convoluted: https://drive.google.com/a/risevision.com/file/d/14My-XbP8o1UgCTzy84QBRM7ODBqsKcms/view?usp=drivesdk

**Comment by ezequielc** [comment]
@PatrickA-RiseVision I tried to replicate and it is working fine for me. Did you try clearing the cache? Thanks!

**Comment by santiagonoguez** [comment]
May be related to the new frame embedding HTTP headers added yesterday.

**Comment by ezequielc** [comment]
@santiagonoguez That is what I thought. Are you able to replicate it?

**Comment by santiagonoguez** [comment]
@ezequielc yes, and it's showing: 'Refused to display 'https://apps.risevision.com/storage-selector.html#/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4&selector-type=single-file' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.risevision.com s3.amazonaws.com *.appspot.com".'

I'm inspecting to see which domain is causing trouble

**Comment by santiagonoguez** [comment]
Fixed by PR above.
