### ISSUE TITLE
Certain addresses not validating when updating address in Company Settings

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#1467]
## Expected behavior:
When a user updates their company address it doesn't fail as long as the address is valid

## Actual behavior:
When a user inputs a certain valid address into their Company Settings it fails with "An exact street name match could not be found" error

## Steps to reproduce:

1. In a Test Company open your Company settings
2. Change the address information to the following:

Street: 4000 High Desert Dr
City: Globe
Country: United States
State: Arizona
ZIP code: 85501

3. Click Save and you'll see the error mentioned above

**Comment by ezequielc** [comment]
@kaden-rise This issue is similar to https://github.com/Rise-Vision/rise-vision-apps/issues/1413. The address is not validated because it is not present in USPS database: https://tools.usps.com/zip-code-lookup.htm?byaddress.
I talked with @sheadarlison and he said that in this case we can close the defect and you should follow up with the user to have their address added to the USPS database. Thanks!
