### ISSUE TITLE
Template usage attribute in HubSpot not accurate for some companies.

### ISSUE THREAD

**Issue by brianloosbrock** [Rise-Vision/rise-vision-apps#1572]
I have come across two companies that don't have accurate values for the attribute 'Rise Company Template Usage'. The two are below.

**Globe Unified School District**
https://app.hubspot.com/contacts/2700250/company/2909201474/
They are using templates but in HubSpot it indicates their not. The last update in the attribute history is Feb 18?
![image](https://user-images.githubusercontent.com/6887543/76121027-661cb500-5fb8-11ea-84a5-e2b0b056d9f1.png)

**Charlotte Catholic High School**
https://app.hubspot.com/contacts/2700250/company/2554305083/
They are using templates but in HubSpot it indicates their not. The last update in the attribute history is Feb 11?
![image](https://user-images.githubusercontent.com/6887543/76121040-6c129600-5fb8-11ea-854a-188b85f4dd91.png)

**Comment by ezequielc** [comment]
Sorry, it auto-closed because I merged the PR but I still want to double check the data. Re-opening. Thanks

**Comment by ezequielc** [comment]
@brianloosbrock There was an issue with the query for Template usage tracking. Basically, it was only counting old Presentation Templates. It didn't include HTML Templates because HTML Templates log to a different table, which was not taken into account on this query.
I updated the query to include both tables, and validated the reported companies have correct values now. You will probably see a significant increase in Template Usage across the board due to that.

@sheadarlison I know you use Template Usage in some KPIs, so you might be interested on this as well.
Presentation Templates logs are in `client-side-events.Widget_Events.template_events` and HTML Templates logs are in `client-side-events.Template_Uptime_Events.events`.

Thanks!

**Comment by ezequielc** [comment]
@mmeiers I forgot to tag you above, you might also be interested on that. Thanks!
