### ISSUE TITLE
Placeholder durations are not being respected

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#159]
**Reproduction Steps**

- Added presentation 1 to a schedule for 10 seconds: https://apps.risevision.com/editor/workspace/20aaf17e-39c3-40a0-90d3-d328d0226968/?cid=3da811c9-e7d0-4e54-86f1-5d458798f236
- Added presentation 2 to a schedule for 40 seconds: https://apps.risevision.com/editor/workspace/56cd0e99-9dbf-43a3-9576-eec0e06e70bb/?cid=3da811c9-e7d0-4e54-86f1-5d458798f236
- Play it on a display
- In under 15 minutes the left-placeholder and right-text placeholders in presentation 2 become out of sync

**Expected Results**

- The placeholders respect their durations and stay in sync

**Actual Results**

- The placeholders are out of sync
- https://drive.google.com/file/d/0B-WhEeWXfRbgVHcwd0Y0Z25XMkhpWWdYalAzWC1mM0xOblFR/view?usp=sharing

**Comment by alex-deaconu** [comment]
Discussed with @sheadarlison and this issue highlights a misunderstanding regarding Viewer's behaviour.

To clarify, when a Presentation is set to play in a Schedule, Placeholder Items that are interrupted before playing their full duration will be skipped the next time the Placeholder is run. For example, in this case we have a presentation with 2 (relevant) placeholders, both with a total run time of 70 seconds. The first Placeholder (ph1) has 7 items running each for 10 seconds. The second Placeholder (ph2) has 5 items, 4 of them running for 10 seconds and the 5th for 30 seconds (total of 70 seconds).

When the Presentation is set to run for 40 seconds as a Schedule item, it will run in the following manner (each item number represents a 10 second interval):
ph1: 1, 2, 3, 4
ph2: 1, 3, 3, 4

ph1: 5, 6, 7, 1
ph2: 5, 5, 5, 1

ph1: 2, 3, 4, 5
ph2: 2, 3, 4, 5

ph1: 6, 7, 1, 2
ph2: 1, 2, 3, 4

--> At this point the second Placeholder (ph2) is out of sync.

Couple of ways to resolve this:
1) Run the Presentation for 70 seconds in the Schedule
2) Set up the Presentation to run twice, once for 40 seconds, the second time for 30 seconds, in the Schedule. Since duplicate items should not be loaded twice in the Viewer there no need to worry about resources. Presentation 1 - 10 seconds, Presentation 2 - 40 seconds, Presentation 1 - 10 seconds, Presentation 2 - 30 seconds.
3) Use the Schedule Item Play Until Done feature and set the first Placeholder as the "Done Placeholder"; however from my testing this may cause sync issues if the first Placeholder (in list order) is not used

To clarify, we tested scenario (1) and it resolves the issue; the Placeholders no longer go out of sync.

Closing. Thanks!
