### ISSUE TITLE
Searching for "HTML" when selecting a widget to add to a presentation returns every widget

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1653]
### What is the expected behavior?
Searching "HTML" in the widgets search returns the HTML widget.

### What is the actual behavior?
Searching "HTML" in the widgets search returns every widget.

### What steps can be taken to replicate the problem?
- Create a presentation from a blank template.
- Create a placeholder
- Click "Widget" to add a widget
- Search for "HTML"

**Comment by ezequielc** [comment]
Thanks @PatrickA-RiseVision .

@sheadarlison Revising this, there is nothing wrong with the code itself, it is just a particularity of our search strategy. We search the keyword in any field of the widget, not only Name or Description, so that it could have a higher chance of presenting a result.
I don't think it is worth revising our search behaviour at this point, so I would propose closing this defect. Please let me know your thoughts. Thanks!

**Comment by ezequielc** [comment]
@PatrickA-RiseVision We talked about this issue at SoS. The conclusion is that it has not a significant impact, so we are not pursuing it right now. I will close it. Thanks!
