### ISSUE TITLE
'Rise Company Subscription Renewal Date' in HubSpot not correct

### ISSUE THREAD

**Issue by brianloosbrock** [Rise-Vision/rise-vision-apps#1660]
We have a field in HubSpot called 'Rise Company Subscription Renewal Date' that tells us the date of the customers next subscription renewal. Currently some of the dates are correct and some are not. The ones that are wrong are are showing very old dates.

Some examples are;

- HubSpot https://app.hubspot.com/contacts/2700250/company/489368913/ and Chargebee https://risevision.chargebee.com/customers/9794132/details

- HubSpot https://app.hubspot.com/contacts/2700250/company/471085604/ and Chargebee https://risevision.chargebee.com/customers/564139/details

**Comment by brianloosbrock** [comment]
@alex-deaconu @ezequielc Can we fix this issue right away? I need for a churn prevention campaign I want to start tomorrow. Thanks

**Comment by ezequielc** [comment]
@brianloosbrock Sounds good, we will give priority to this. Thanks!
@alex-deaconu fyi

**Comment by alex-deaconu** [comment]
@brianloosbrock to confirm, the fix for the initial issue with the One Time purchases has been put in place. To confirm, no Subscription that is not in Chargebee should be counted for the Renewal Date value.

I've validated with the examples above and the renewal dates appear as expected.

Closing. Thanks!
