### ISSUE TITLE
Cross-site cookie warning

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#1686]
Error shown below is reported by Anywhere extension. Not clear to me why our content is referring to www.risevision.com. I thought request from our content would be for a subdomain such as preview.risevision.com. 

![image](https://user-images.githubusercontent.com/6854911/81986355-48de1580-95fd-11ea-9d8b-319987f08eaa.png)

**Comment by ezequielc** [comment]
@tejohnso When I open the Shared Schedule URL outside of the extension I don't see this warning. It only appears when running in the extension. 
I took a look at the extension code but could not find a reference to risevision.com. I am wondering if it could be related to Segment or maybe some different browser policy for extensions. Thanks!

**Comment by tejohnso** [comment]
It's not happening for me in the extension.
![cookie](https://user-images.githubusercontent.com/1511535/81990364-04f30c80-960d-11ea-8266-aeb2dfac08d6.png)

**Comment by alex-deaconu** [comment]
<img width="269" alt="Screen Shot 2020-05-15 at 10 39 22 AM" src="https://user-images.githubusercontent.com/6218188/82063702-cf483500-9699-11ea-93b4-ad082f5d20da.png">

**Comment by alex-deaconu** [comment]
@alanclayton from taking a look at this in another version of Chrome (they have a tab that analyzes these errors), the cookies listed are from:

- Google Analytics `ga` & `gid`
- Segment `tld`
- Amplitude

These cookies are being set on both `preview.risevision.com` and `.risevision.com` in Viewer. The second screenshot shows the analytics cookie being added to a template and causing a similar error.

To confirm, I do not know of any cookies we set ourselves explicitly for the extension, outside of these 3rd party cookies.

At this point Segment sets some cookies correctly (`SameSite=Lax`) not sure why the `tld` one is not. Amplitude and Google Analytics do not seem to do so.

I don't think it's an issue either way, because Chrome announced that it is pulling the actual enforcement of these issues for the time being. And once they do start enforcing (we've had this issue with Apps before), I'm sure these big players will start complying.

My suggestion is to close at this point and revisit if it becomes enforced. @ezequielc @tejohnso FYI.

Thanks.

**Comment by alanclayton** [comment]
Okay. Thanks @alex-deaconu
