### ISSUE TITLE
Display Monitoring offline emails sent for newly created displays that aren't activated yet.

### ISSUE THREAD

**Issue by brianloosbrock** [Rise-Vision/rise-vision-apps#1708]
I created the following displays and upon creation each one of them triggered an offline email from display monitoring that was sent to the customer.

The Display ID's are;
- 7JMUJ4AGS2XZ
- 9HCSNAP7XK3U
- 6ZT3GJG6A5W7
- QQ8RTPRMHV36
- AKSKPS537XTN
- BX6WZ74GYQ82
- ZX6HDMPCVBHN

I used a batch creation process created by @alexey-rise to create these displays. I don't know if thats related or not. Either way the creation of these displays should not be triggering the offline emails from display monitoring.

**Comment by tejohnso** [comment]
@brianloosbrock If the display exists in datastore and has been configured for monitoring then it will be monitored. Which means if it is offline an offline notice will be sent. Why would those displays be exempt? Were you expecting that the displays should have to be online once before receiving an offline notice? We don't have that rule.

Let's say we put that rule in and you set up your display, and it has a networking problem with messaging service / bigquery but it looks fine to you because all of the networking fallbacks worked to show content. So it never indicated it was online. Then something happens and it goes offline. In that case we wouldn't send an offline event. Nobody would know that there's an issue with that display.

So the way it works, they get the offline notice when it's offline, even if the display never communicated online status. This makes it clear that as far as Display Monitoring is concerned, that display is not online, and is not considered to be online until the online notice is received.

We can change it, but we'd be sacrificing some certainty. We could end up with displays for which monitoring isn't working and nobody would know about it until we get a complaint that a display was off and no email was received.

For your use case, if they don't want to receive the offline notice, maybe you can leave the checkbox unchecked, and then wait until they give you the go ahead that their displays have been set up before enabling monitoring. 

@alanclayton @ezequielc FYI - any other suggestions?

**Comment by tejohnso** [comment]
@brianloosbrock per our discussion, I'm going to close this for now since: 

 - We don't want to get into creating special process exceptions for this one user
 - We haven't had a complaint about this functionality other than from this one user
 - It's not certain that most users going forward would prefer the changed behaviour vs current
 - You have already spoken with this user to reduce impact of this issue for them
