### ISSUE TITLE
During user editing or creation, an email with a hyphenated domain with 3 parts incorrectly fails validation.

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1727]
### What is the expected behavior?
As a user, I can provide my email address on my account so I can be contacted by Rise Vision.

### What is the actual behavior?
If my email address contains a hyphen between two dots in the domain, validation fails and I cannot save my profile or make changes to it.  It's accepted as a username.

### What steps can be taken to replicate the problem?
1. Log into a rise vision account.
2. Attempt to create a user with an email address that has a pattern like: 
"some.user@fake.email-address.com"
3. Click save.  It will fail saying the address is invalid.

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision we have deployed a fix for this. To confirm, we have updated the validation to allow these types of emails. Actually it's a lot more relaxed now. However, the Core also performs a "domain check" to see if the domain is valid, so that should catch emails that are really off but pass the initial validation.

Closing. Thanks!
