### ISSUE TITLE
Some addresses give you the error “address is out of range” when you are following through the purchase process

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1743]
### What is the expected behavior?
As long as you enter a valid address, you should be able to complete checkout.

### What is the actual behavior?
If you enter an address that is not in Avalara's database, you get the error message “address is out of range”, and you cannot enter in your address.

### What steps can be taken to replicate the problem?
Use the address 1 Backbone Rd. Princess Anne, MD 21853 when checking out, and you will get the error message. The only way to get past this is to enter "General Delivery" in Line 2 of the address.

**Comment by ezequielc** [comment]
@robb-price Similar to issues #1413 and #1467, the provided address is not found in USPS database (https://tools.usps.com/zip-code-lookup.htm?byaddress), therefore it fails Avalara validation, and it would not be possible to calculate taxes.

@alanclayton I saw Byron's question in Slack, so I am wondering if we are considering removing Avalara address validation. Just as a reminder, we also rely on address validation to provide better data to the Weather Component.
Please let me know how to proceed. Thanks!

**Comment by alanclayton** [comment]
@ezequielc my understanding is that we are exempt in 48 of 50 states. if accurate, we could remove the check for the 48 we are exempt in. thoughts? 

How are addresses validated for credit card billing?

**Comment by ezequielc** [comment]
@robb-price As per discussion in this [card](https://trello.com/c/OfLDBTUd/6349-issue-1743-some-addresses-give-you-the-error-address-is-out-of-range-when-you-are-following-through-the-purchase-process-2), when an address fails validation we are presenting a message the the user if the want to change it to General Delivery. If confirmed, we update the Unit field so that the validation can be "skipped". Thanks!
