### ISSUE TITLE
multiple hubspot companies for one rise vision company

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1760]
Can you please confirm if this company: https://app.hubspot.com/contacts/2700250/company/1002718733/

Should be merged into this company: https://app.hubspot.com/contacts/2700250/company/986613089/

And do we know what caused the duplicates?

**Comment by ezequielc** [comment]
@alexey-rise @tejohnso I assume this is related to Hubspot sync, right? Should you grab it? Thanks!

**Comment by alexey-rise** [comment]
@sheadarlison you are correct, https://app.hubspot.com/contacts/2700250/company/1002718733/ needs to be merged into https://app.hubspot.com/contacts/2700250/company/986613089/ because only https://app.hubspot.com/contacts/2700250/company/986613089/ is linked to our DB and is being updated by the server side jobs.

On the other hand https://app.hubspot.com/contacts/2700250/company/1002718733/ is not linked to anything and our system is not aware of it.

As for what caused the duplication, both Hubspot records were created back in Oct 2018, since then we have identified and corrected a number of issues that caused data duplication, it is difficult to say which one of them was responsible for this particular case.

@ezequielc @alanclayton FYI.

**Comment by sheadarlison** [comment]
Thanks @alexey-rise I will merge these.
