### ISSUE TITLE
Backgrounds added as a Background Item in Presentation or Placeholder Settings don't cache

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1826]
### What is the expected behavior?
All images in a Presentation will cache, regardless if they are added with the Image Widget, or as a Background in the Placeholder or Presentation.

### What is the actual behavior?
Backgrounds added as a Background Item in Presentation or Placeholder Settings don't cache. This means if they are very large, they will download every time causing bandwidth issues, and they will not work in offline play.

### What steps can be taken to replicate the problem?
Simply add an Image as a background item or in the Placeholder Settings, and notice it is not downloaded to the cache folder. 

There is an easy workaround here, just add the background as an Image Widget.

--

**Comment by ezequielc** [comment]
@alanclayton I am not sure if this is worth pursuing. The reason it is not cached for offline is because Presentation Background is added directly in CSS, it does not use Image Widget (also related to https://github.com/Rise-Vision/rise-vision-apps/issues/377, which we decided not to pursue), therefore it relies on browser cache.

To update it to use Image Widget would require a significant change in Presentations architecture, which is not something we would like to invest at this time. Thoughts? Thanks!

**Comment by alanclayton** [comment]
@ezequielc I agree that this is not something we want to invest in. @robb-price I think we should encourage users to migrate to using a template. If that doesn't work apply your suggested work around. Let us know if you are good with that. Thanks

**Comment by robb-price** [comment]
@alanclayton @ezequielc Understood the commitment and the time required, but from the customer side, it doesn't work as we say it does, specifically it doesn't cache for offline play, and the experience kind of sucks. I get we aren't going to fix this now, but are we going to track this and consider it for the future improvement? Also, where can Support put things like this? Something like a "Not a bug, but an improvement in behavior" list?

**Comment by ezequielc** [comment]
@robb-price I will close this. Re your question, Alan may clarify further but I believe you should keep tagging him on tickets, so that he can be aware of the ideas for consideration. Thanks!
