### ISSUE TITLE
CAP Alert Templates have a delay when populating text.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1884]
### What is the expected behavior?
Regardless of the Presentation you use, the text in the CAP Alert should populate at the same speed.

### What is the actual behavior?
When you use one of the Pre Designed Templates, there is a noticeable delay in the text changing to the text being sent by the Alert.

### What steps can be taken to replicate the problem? 
These two videos show the Display showing an Alert sent with the Pre Designed Template, and one with the Blank Presentation Template. Notice the PreDesigned CAP Alert Presentation takes longer to populate the text.

Blank Presentation Template: https://drive.google.com/file/d/1rOGsRTIwsJshu-txF4yilK7itRN82ko8/view?usp=sharing

PreDesigned CAP Alert Template: https://drive.google.com/file/d/1r_nrFxvlSZFRW3CwdYP72P3wqaJ-pkv9/view?usp=sharing

**Comment by ezequielc** [comment]
@tejohnso I think you/Alexey should take this as it seems related to the Alert changes Alexey worked on. Thanks

**Comment by alexey-rise** [comment]
@ezequielc @tejohnso The issue is caused by the delay between the display updating its content (and starting to show the Alert template) and template attribute data (which contains the actual alert text) arriving at the display from GCS. The Core writes the attribute data to GCS synchronously before sending the alert content to displays, so it's not a timing issue on the server side, the issue is on the client side and I am not sure how much we can actually do about it.
I think the best remedy for this issue would be not to show the placeholder text (i.e. **%HEADLINE%**) until the attribute data arrives, however the best place for that functionality would seem to be in the common template code, which I am not very familiar with. I am wondering if @stulees or @mmeiers would have a better idea of what could be done?

**Comment by mmeiers** [comment]
@ezequielc @alexey-rise 
Just to clarify the issue @robb-price and the client are pointing out is that the old CAP alert template with the old editor loads data significantly faster than the new one that was built as an HTML Template. Sometimes 5-7 seconds slower. While I agree that Hiding %HEADLINE% is good practice and we should do it for the future templates we have planned it's not going to resolve the issue for this client considering they specifically benched marked this against the old one (they will just complain that it is blank for a period of time). If the problem is with infrastructure and the difference between how we have to handle Alerts in HTML templates vs old editor templates I think the better option is reverting to the old template in the editor until we have a better solution.

**Comment by mmeiers** [comment]
Perhaps we should discuss at scrums of scrums tmw?

**Comment by stulees** [comment]
I agree with @mmeiers , this needs further discussion as it doesn't seem to me like we can resolve the delay in populating the text. If we wanted to not show the placeholder as a compromise, then the template itself is best to address this as opposed to common-template because common-template is just facilitating the data. Unless I'm missing something specific with CAP alerts.

**Comment by alexey-rise** [comment]
@mmeiers @stulees the fundamental difference between the old and the new alert presentations is that the old one had the alert text already embedded in it, while the new template-based one relies on template attribute data (where the alert text is) to be retrieved separately from the presentation itself. As long as this difference remains, template-based presentation will always be slower to show alerts and the difference will remain for as long as template architecture remains as it is (not saying that it needs to change, just saying that this is why we see what we see).

**Comment by mmeiers** [comment]
@alexey-rise Got it thanks. Just to clarify the reason we rely on attribute data is not just because we are using rise-text. It's also because of the template architecture, correct? I just want to confirm there is no way to rebuild the Template to embed the alert as the old one was.

**Comment by alexey-rise** [comment]
@mmeiers the problem is that template presentation is not coming from a DB on our server, it is created separately, stored separately and more importantly the same template can be used for many companies (so even if we could locate the template and patch it directly to embed the alert text in it, it would show up for all companies, not just the one that got the alert).

**Comment by tejohnso** [comment]
> the template itself is best to address this as opposed to common-template because common-template is just facilitating the data.

@mmeiers given this responses from @stulees and the responses from @alexey-rise would you agree that this is best resolved within the individual templates? And if so, can you take this?

**Comment by robb-price** [comment]
As discussed, Support is fine with closing this issue.

@mmeiers @stulees @tejohnso @alexey-rise FYI.

**Comment by tejohnso** [comment]
Short recap of the discussion: 

----
Mat mentioned he didn't think the proposed solution would satisfy a user who is comparing editor alerts vs template alerts since template alerts are taking a few seconds more to display and showing nothing until the data arrives would not speed up the render latency.

Byron was wondering why there was benchmarking being done to compare editor alerts vs template alerts.

Brian indicated he would discuss further with support and likely close the issue.

----

To properly correct the issue we'd have to re-architect the way template alerts work to try to save a few seconds during data fetch. Likely to be a low ROI endeavour.
