### ISSUE TITLE
A Rise Vision company has two separate company accounts in Hubspot.

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/rise-vision-apps#1898]
### What is the expected behavior?

For each Rise Vision company, there is one corresponding company in Hubspot.

### What is the actual behavior?

There are two companies for St. Johns:

https://app.hubspot.com/contacts/2700250/company/801956399
https://app.hubspot.com/contacts/2700250/company/920076721/

### What steps can be taken to replicate the problem?

View both companies above in Hubspot and confirm they both have the same Rise Company ID: f104a48a-6578-4df9-8cd6-befcd04c1129

**Comment by alexey-rise** [comment]
@jrkuchta the issue has occurred in Sep 2018. We have fixed several issues related to Hubspot company asssignment since then so it is not easy to establish which of them was responsible for this particular instance. Currently https://app.hubspot.com/contacts/2700250/company/920076721/ is linked to the company f104a48a-6578-4df9-8cd6-befcd04c1129 in our system,  https://app.hubspot.com/contacts/2700250/company/801956399 is not linked to anything. 

I would suggest that data from https://app.hubspot.com/contacts/2700250/company/801956399 should be merged into https://app.hubspot.com/contacts/2700250/company/920076721. 

If that is not practical, please let me know and I will reassign https://app.hubspot.com/contacts/2700250/company/801956399 to company f104a48a-6578-4df9-8cd6-befcd04c1129 in our system and then https://app.hubspot.com/contacts/2700250/company/920076721 would need to be merged into https://app.hubspot.com/contacts/2700250/company/801956399.

@tejohnso FYI

**Comment by sheadarlison** [comment]
@alexey-rise thanks, I've merged them.

**Comment by sheadarlison** [comment]
@alexey-rise @tejohnso 

How do you check if a company is linked to something in our system? 

I'd like to correct this problem everywhere it exists and it looks like right now there are about 1,700 companies with duplicates (or triplicates) in HubSpot.

**Comment by sheadarlison** [comment]
@tejohnso @alex-deaconu also, can you please take a look at these companies: 

https://app.hubspot.com/contacts/2700250/company/580842947/
https://app.hubspot.com/contacts/2700250/company/4203255107/ (duplicate created July 22, 2020) 

---

https://app.hubspot.com/contacts/2700250/company/591846894/
https://app.hubspot.com/contacts/2700250/company/4158935052/ (duplicate created July 13, 2020)

---

There's lots of other recent examples, (see the All Companies tab in the sheet linked above) do you know how these are being created?

**Comment by alexey-rise** [comment]
@sheadarlison will get back to you with the list. Thanks

**Comment by alexey-rise** [comment]
@sheadarlison please see the following spreadsheet as requested and let me know if you want me to change anything:
https://docs.google.com/spreadsheets/d/1zeCwJMAbXU7SF8VQSCzIBXEC92FfVO7GTkUmduWzKtA/edit?usp=sharing

**Comment by sheadarlison** [comment]
Thanks @alexey-rise I think that covers what I need. 

Are you still looking into the more recent duplicates I mentioned in my follow up comment?

**Comment by alexey-rise** [comment]
@sheadarlison yes, I am still looking into those and will update the issue once I have the conclusion.

**Comment by alexey-rise** [comment]
@sheadarlison I have identified and fixed an issue that led to creating duplicated companies and contacts (https://github.com/Rise-Vision/hubspot-connector/pull/131).

**Comment by sheadarlison** [comment]
@alexey-rise thanks
