### ISSUE TITLE
Display Settings UI is shifted when the assigned schedule's name is long

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1971]
### What is the expected behavior?
The layout is retained regardless of user entry.

### What is the actual behavior?
If a user gives a Schedule a long name and then assigns it to a Display, the Display Settings page's layout is shifted while looking at that Display.

![image](https://user-images.githubusercontent.com/40774237/90407044-60092500-e07c-11ea-8e38-5d6fd1c5e3bc.png)

### What steps can be taken to replicate the problem?

- Create a schedule with a long name (33 chars in the example)
- Assign a Display to the schedule
- View the Display Settings for that Display

**Comment by ezequielc** [comment]
Thanks @PatrickA-RiseVision.

@jasoncaldwell This was actually intentional, but looks like it was not a good idea. When the name was long, I decided to stack the name/buttons. But I am wondering if we should set a max-width and use ellipsis instead. 

The problem gets worse on a smaller screen, and my idea was to hide the Edit Schedule button in such case:
<img width="738" alt="Screen Shot 2020-08-17 at 1 54 06 PM" src="https://user-images.githubusercontent.com/7738553/90422439-3d353b80-e091-11ea-9e77-a5a2ea0deeeb.png">
 
Please let us know if you have any suggestions. Thanks!

**Comment by jasoncaldwell** [comment]
@ezequielc Same, my feedback would be to truncate the name length in the select menu, if possible. Regarding the "Edit Schedule" and "Share" buttons, feel free to reduce the width of those buttons on resize, as well. I'm okay with stacking those items on top of each other, just as long as the rows have vertical space between them. Let me know if that makes sense!

**Comment by ezequielc** [comment]
@jasoncaldwell Thanks for the feedback, I will try to implement as per your recommendation.
