### ISSUE TITLE
When no presentations created from templates exist in a schedule, preview does not work.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#1973]
### How to recreate
- Create a new Schedule
- Add a presentation created from template to that schedule and save.
- Delete the presentation from the schedule.
- Add a presentation created from blank to the schedule and save.

### What happens
Schedule preview shows "There are no updates to show right now. Have a great day!"

### What should happen
Presentation created from blank should show in preview, or the preview should reflect that it cannot show presentations created from blank.

[Example Schedule](https://apps.risevision.com/schedules/details/e2e30eb1-b06a-4c88-9e2e-125e50d1fc2e?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957)

**Comment by ezequielc** [comment]
@btfrise Schedule preview follows the same rules as Shared Schedules. The Presentation you added does not play on Shared Schedule (probably due to a HTTP page on Web Page widget).

I checked with another Presentation and it works for me: https://apps.risevision.com/schedules/details/1fd79103-5f01-4129-be1d-85b3b872460b?cid=f114ad26-949d-44b4-87e9-8528afc76ce4.

Let me know if we can close this. Thanks!

**Comment by btfrise** [comment]
@ezequielc This is a confusing message to show users and it's generating tickets and touches. If a schedule preview cannot be shown due to in incompatibility, the message shown should reflect that, not that there are no updates to show.

**Comment by ezequielc** [comment]
Thanks @btfrise, that is a good point.

@alanclayton fyi, I think we should try to follow Blake's recommendation and show a more specific message if the content can't be shown. Ideally this message would only appear in Apps (i.e. Shared Schedule viewers would continue to see the current message). Let me know your thoughts. Thanks!

**Comment by ezequielc** [comment]
Note: As discussed in SoS, we will address this as part of https://trello.com/c/AAJJRXWD/868-stop-http-errors-on-entry-share. Thanks

**Comment by alanclayton** [comment]
@ezequielc @btfrise I took a look at Blake's presentation and the reason it does not show in a shared schedule is because it has video widget. Any Presentation with video is skipped because we do not have the mechanisms in place to control our bandwidth. These mechanisms should be in place early October. 

If you remove the video widget, as I did in [this copy of Blake's presentation](https://apps.risevision.com/editor/workspace/8686ba63-4d31-4ea6-bbcf-a87471bed077?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957), it will show on the embedded preview. But this reveals other issues;

1. The web page widget does not tell a user to use HTTPS
2. The web page widget does not default to using HTTPS if protocol is not specified. [The user simply added the url he-man.org and it was added to the HTML as HTTP.](https://www.screencast.com/t/b0WMXbSOfTqe)
3. The web page widget is able to open http://www.he-man.org in preview because preview is opened as an insecure URL (non-https) 
4. The web page widget can't open the URL in a shared schedule because shared schedules are opened as a secure URL (https). 

@ezequielc do you know why we don't open preview with a secure URL?

**Comment by alanclayton** [comment]
@btfrise just to clarify, from your perspective the support touches you are seeing are specific to the situation where the message "There are no updates to show right now. Have a great day!" is shown instead of the presentation. 

Here are the scenarios where we intentionally skip a presentation that could result in this message being shown;
1. the presentation has video widget or video component
2. the presentation is configured to use the twitter widget (our twitter templates work no problem)
3. the presentation is configured to show financial data.

**Comment by ezequielc** [comment]
@alanclayton We open Presentation Preview as HTTP to avoid the HTTPS blocks that we are familiar with. If we decide to open it as HTTPS, all HTTP urls would be blocked and prevent users from previewing their content. Thanks

**Comment by alanclayton** [comment]
@ezequielc But we now have inconsistencies that cause confusion/frustration. I preview my content and all looks well, but then it doesn't show up for others when I share it with them. 

I think we need to correct this. Thoughts?

**Comment by ezequielc** [comment]
@alanclayton Right, but if we change to HTTPS we are going to have the inconsistency the other way around. Displays are going to show HTTP content, but users will not see that content on Preview.
It is a tricky situation, but I am more inclined to continue to show in HTTP so that they can see at least in one place what the Display is going to show. Thoughts?

**Comment by alanclayton** [comment]
@ezequielc player opens viewer as HTTPS. The discrepancy is that http url will still show on player because our version of chrome which we need to update.  The inevitable outcome is that http URLs don't work I think we need to define the requirements to correct this.

**Comment by ezequielc** [comment]
@alanclayton Good point. And by revising the epic, I saw that we are going to present a clear message to the user ('[URL] could not be opened because it is insecure. Please update the URL to use HTTPS'), so I am good with changing it to HTTPS. Thanks!

**Comment by alex-deaconu** [comment]
We now show an error warning in Apps when an `http://` URL is used in a Schedule.

To confirm, there are other items that we skip, videos, financial, etc that do not have any indication that they will not show in the Shared Schedule.

The decision at this point is to not show a notification in the preview as discussed above.

Closing. @alanclayton @btfrise fyi. Thanks!
