### ISSUE TITLE
Last Connection Time for some displays is incorrect

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#2050]
### What is the expected behavior?
The Last Connection Time should show the correct time that the device was last online.

### What is the actual behavior?
For the displays listed below, they show a different last connection time in BigQuery vs what is shown in the UI.

### What steps can be taken to replicate the problem?
Use this query: https://docs.google.com/document/d/1SfNjbbZr-SBWha3h48-1z0KcUgIxzUn5XteuDan8C9A/edit to view the Last Connection time for these Displays:
- 3KAMQ4GK89RJ
- 5B8T95ZEPTSQ
- 6QHV8W6S93CX

and notice that it does not match what is listed in the image below
![RiseError](https://user-images.githubusercontent.com/6862256/93901871-f7d5e080-fcc4-11ea-8628-2d72e8951d42.JPG)

**Comment by alexey-rise** [comment]
@robb-price the issue is *partially* resolved in a sense that any display that has connected since about Sep 10 will have the correct last connection date, but displays that have not connected since then will still have incorrect last connection date. However it will be correct as soon as they go online.
In order for the inactive displays like the ones you listed to show correct last connection date we would need to import data from BQ into Core DB which will require some time and effort. The question is: is that really necessary or is the current fix good enough?

**Comment by robb-price** [comment]
@alexey-rise The user has not turned the displays on yet, so I think we can safely close this, and will revisit if he discovers otherwise when he turns them back on.
