### ISSUE TITLE
Not all the download player links work in-apps

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#2163]
https://www.screencast.com/t/tLkmCbQpWu

**Comment by ezequielc** [comment]
@alanclayton  @tejohnso Based on [here](https://www.ghacks.net/2020/10/08/chrome-is-blocking-downloads-here-is-why/) and [here](https://blog.chromium.org/2020/02/protecting-users-from-insecure.html),  Chrome 86 started to block HTTP downloads of .exe files from HTTPS webpages.

Due to that, we need HTTPS links for downloading players. I tried to use https for our [current link](http://install-versions.risevision.com/installer-win-32.exe), but the browser shows a certificate error. So I am wondering if @tejohnso could provide that. Thanks!

@alex-deaconu fyi

**Comment by tejohnso** [comment]
The complication is that Cloud Storage doesn't support custom domains with HTTPS on its own. 

We could change the links to use the googleapis.com domain via https. For example `https://storage.googleapis.com/install-versions.risevision.com/installer-win-32.exe`

Otherwise, if we want to keep using install-versions.risevision.com but with HTTPS we'll need to use a load balancer (similar to widgets.risevision.com)

**Comment by ezequielc** [comment]
@tejohnso Using googleapis.com is a good solution to me. We already rely on it for storage downloads and screenshots, so it would not add to the network requirements. I will proceed with that. Thanks!

**Comment by ezequielc** [comment]
@btfrise I noticed that download links in the Help Center articles are not working as well. You might want to follow the conclusion here and update the links there as well. Thanks!

**Comment by ezequielc** [comment]
@btfrise @tejohnso @alex-deaconu I just talked with @alanclayton and he is ok with the proposed solution.
I will proceed updating Apps and Core emails. Thanks!
