### ISSUE TITLE
Company has a cancelled subscription that is showing active

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#2165]
Company [Clarks](https://apps.risevision.com/billing?cid=9530ae87-bbc3-4a72-8593-adf9199464ce) has a cancelled subscription (ID HqVjt0KRUb3WY62Wt6). It is showing as cancelled in chargebee, but is still active in the rise vision company and is still granting licensing.

**Comment by ezequielc** [comment]
@btfrise Just to confirm, I do see the subscription as Active in the Billing page, but the company shows as not subscribed and does not have licenses to be used. I will investigate why the subscription is being reported as Active. Let me know if I am missing something. Thanks

<img width="1423" alt="Screen Shot 2020-10-29 at 1 44 00 PM" src="https://user-images.githubusercontent.com/7738553/97605456-678a6a00-19ed-11eb-9716-02d0917f246b.png">

**Comment by btfrise** [comment]
@ezequielc you have this correct. thanks!

**Comment by alex-deaconu** [comment]
@btfrise to confirm, the data seems to have been inconsistent for this Subscription.
Chargebee/Datastore which had the correct Cancelled value. The list response had the incorrect value. I've rectified by rerunning the Chargebee webhook call.

Our investigation points to an indexing issue at this point, however since we've never seen this before we will not pursue further at this time. That may change if we see it happening again.

Closing. Thanks!
