### ISSUE TITLE
[UI Review] Consolidated feedback for billing & invoice details

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2276]
### Subscription Name As A Hyperlink

Is there a reason for not using the subscription name as a hyperlink, as per [the design](https://share.goabstract.com/0648eb08-cf74-4d2b-a41d-c476fe91ac00?mode=design&sha=4dc34a8b54119110e8215177e58d1aa9c0e2fbca)?

![Billing___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/101419616-64bd4780-38be-11eb-8bad-94718449676c.png)

I'm fine with it as-is for the time being, but was curious.

---

### Padding Under Titles

Padding under the titles in the Account & Billing page should be a maximum of `10px`.

![Billing___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/101419806-cbdafc00-38be-11eb-88b3-edaf68feb1ed.png)

---

### Period missing from error message

Period missing from error message

![Invoice___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/101419939-1e1c1d00-38bf-11eb-8d3e-7356bc6dc6c2.png)

---

### Visited color for hyperlinks

Hyperlinks shouldn't have a visited color.

![Invoice___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/101420167-9b479200-38bf-11eb-967b-b35a8add9a7b.png)

---

### Dead link

Link is dead. Is the in-app help menu supposed to appear?

![Invoice___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/101420265-ca5e0380-38bf-11eb-96dd-171079814bea.png)

---

### Copy for "Education Discount:"

Should this say "Education Discount:"?

![Invoice___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/101420387-07c29100-38c0-11eb-9b28-c7a9fe0ba585.png)

**Comment by ezequielc** [comment]
@jasoncaldwell I have a PR (https://github.com/Rise-Vision/rise-vision-apps/pull/2278) ready with most of the fixes, just want to confirm two points:

1.  Subscription Name As A Hyperlink: the reason we didn't add a link is because we haven't worked on the Subscription Details page yet, we just left what was in place and updated to match the new style. We will add a link it once we work on the Subscription Details page if that is good with you.

2. Copy for "Education Discount": we are showing what is provided from Chargebee, and I've confirmed it matches to the PDF invoice that Chargebee generates. To change this, we would need to request Debbie/Brian to update it in Chargebee. Let me know if you think it is necessary or we can leave as is. 

Thanks!

**Comment by jasoncaldwell** [comment]
@ezequielc Agreed on both points. Re: "Education Discount" copy, I think it needs to be changed, but I don't think it needs to be done none, especially if it requires a coordinated effort. I'll add this to the backlog. For me, if I was a new user, I wouldn't know what an "Education" line item means.

Thanks!

**Comment by ezequielc** [comment]
@jasoncaldwell Sounds good. Given that, I will go ahead and close the defect. Thanks!
