### ISSUE TITLE
Delete Company dialog does not identify the Company

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2506]
### What is the expected behavior?
You can delete your company if you want to, but it should be really hard to do it by accident.  The modal to delete the company should let you know which company you are deleting so you don't delete the wrong one.

### What is the actual behavior?
The modal to delete the company doesn't identify the company you are deleting, so it's possible to accidentally delete the wrong one.

![image](https://user-images.githubusercontent.com/40774237/113450765-e9385680-93d6-11eb-8d90-8741379b6ed0.png)

### What steps can be taken to replicate the problem?
1. Try to delete a company OTHER THAN RISE VISION by clicking on your username > Company Settings > Delete
2. The company name is not shown on the dialog

**Comment by alex-deaconu** [comment]
@jasoncaldwell looking for some quick feedback on this functionality and wording. Our thinking is to actually have them type in the company name, rather than simply DELETE. For simplicity, we will provide the name for them inline, so they can copy and paste if needed. Please see below for suggested wording:

Title: Delete Company?
Text: Are you sure you want to delete this Company? This operation cannot be undone! Please type **company name** to confirm.

@ezequielc fyi. Thanks!

**Comment by jasoncaldwell** [comment]
@alex-deaconu No strong preference here re: what to type in order to confirm deletion. One drawback I see to having someone enter a company name to confirm deletion is when the company name has ambiguous characters ("0" vs "O", etc.) or when the name is long and complicated, or could even extend beyond the viewable area of the modal. The variable nature of the company names gives me anxiety.

Either way, I agree with @PatrickA-RiseVision. Somewhere in the dialog we should highlight the company name.

@ezequielc FYI.

Thanks!

**Comment by alex-deaconu** [comment]
@jasoncaldwell thanks for the feedback! We will not add the extra step for entering the name, just modify the wording. We can change it later if needed. Thanks!

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision we have updated the wording for that modal to include the Company Name. Closing. Thanks!

<img width="680" alt="Screen Shot 2021-04-28 at 12 33 20 PM" src="https://user-images.githubusercontent.com/6218188/116439821-f69e0080-a81d-11eb-87b7-90c269dc3828.png">
