### ISSUE TITLE
Can't delete presentations since they are in schedules, but those schedules do not exist

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#2508]
### What is the expected behavior?
You should be able to delete a presentation that is not in a schedule.

### What is the actual behavior?
Certain presentations can't be deleted because they are in schedules, however, the schedules do not exist.

### What steps can be taken to replicate the problem?
In this video, you can see the steps to create this: https://drive.google.com/file/d/1w8x3iUN9tH_gla2ReJoOs0indpUQExkn/view?usp=drivesdk

**Comment by alexey-rise** [comment]
@robb-price The issue is not that you can't delete presentations that belong to non-existent schedules, because the schedule actually exists:
![image](https://user-images.githubusercontent.com/7119180/113917513-49504380-97af-11eb-9690-5817b419da85.png)

The issue is that you are unable to find that schedule from Apps.

**Comment by alexey-rise** [comment]
@robb-price I have completed my investigation of this issue and found that there is no issue, the system works as expected. The cause of the problem is our use of client content in our test schedules, please see this video for detailed explanation: https://drive.google.com/file/d/1dFNzHqTm06FJ6JfvsrCdgfGb-xMMMITS/view?usp=sharing

**Comment by alanclayton** [comment]
@ezequielc FYI..you may want to watch Alexey's overview. thanks

**Comment by ezequielc** [comment]
@alanclayton @alexey-rise @robb-price Yeah, I created that schedule programatically using our APIs, to validate a problem we were facing with timelines. Sorry about that. 
Robb already removed the presentation in question from my Schedule, but I went ahead and deleted the schedule itself, as it had some other presentations. Thanks!

**Comment by robb-price** [comment]
@alanclayton @alexey-rise @ezequielc Thanks for the explanation in the video, and I agree that this is not an issue, since users cannot add presentations that do not belong to their account to their schedules. Moving forward, the only thing I would suggest is ensuring you remove a presentation from a schedule that has been added in this manner.

Closing this, as it has been corrected for the user.
