### ISSUE TITLE
[Canva Integration] No prompt for Canva size

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2576]
Issue: Please see this video:

https://www.loom.com/share/d05e856d10534ee9989158dc7ec92fed

**Comment by alex-deaconu** [comment]
@jasoncaldwell unfortunately, the beta branch was out of date. A change had been staged there and not removed. This was corrected, and now beta should point to master.

Just a note, this may happen from time to time since we sometimes need to validate changes with the beta branch, however we need to be more attentive and revert it.

Closing. Thanks.

**Comment by jasoncaldwell** [comment]
@alex-deaconu Thanks!
