### ISSUE TITLE
Branding logo is showing up sporadically 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#2669]
https://apps.risevision.com/editor/list?cid=f89f252c-534c-4a83-813c-39563f0b6b7e

1. I tried uploading a PNG Airtame logo and it didn't show 
2. I then tried uploading an SVG Airtame logo and it didn't show 
3. I then tried uploading a PNG Rise Vision logo and it sometimes showed 

Using the Rise logo, branding logo is not working in 

- Copy of History - On This Day - Video

It is working in: 

- Copy of Zoned Embedded Centered
- Copy of Zoned Embedded School Slant
- Copy of Graduation Announcement

The Airtame logos didn't work at all.

**Comment by alex-deaconu** [comment]
To confirm, the png and svg images seemed to be corrupt, ie. they could not be opened in a browser. This caused the logo not to show.

However, because the png was corrupt, the thumbnail generation was failing, which caused a failure in apps. This was corrected with the attached release.

Also, in the "Copy of History - On This Day - Video" presentation, the branding logo was overwritten by the file that was failing hence was not showing up.

@sheadarlison fyi. Closing. Thanks!
