### ISSUE TITLE
There is no way to schedule content for the "5th" weekday of a month

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2714]
### What is the expected behavior?
Timelines are used to control when content from a schedule is shown on the display.  For example, you can show content on a specific week of the month, on specific days, etc.

### What is the actual behavior?
The options for weekly timelines are first, second, third, fourth, and last, so in a month with 5 Sundays there's no way to show content specifically on the 5th Sunday.  You could choose "Last", but "Last" is also sometimes the 4th Sunday, which would cause a schedule conflict.

### What steps can be taken to replicate the problem?
Create a schedule that recurs based on which week of the month it's in.  i.e.

Week 1
Week 2
Week 3
Week 4

Without being able to schedule a week 5, a month with a partial 5th week will show no content for a few days.
Alternatively, add a "Last Week" timeline.  You'll get conflict on the 4th week in a month without a partial 5th week.

**Comment by ezequielc** [comment]
@jasoncaldwell fyi, this is the defect we need your input, whether we want to to pursue it or not and what would be the proposed approach, as per Patrick's suggestions. Thanks!

**Comment by jasoncaldwell** [comment]
@ezequielc My thought is that it's a defect worth fixing, but I'll leave it up to determine priority and how it fits in to the current sprint. In terms of solution, I think the easiest thing would be to simply add "Fifth" as an option in the dropdown:

![Screen Shot 2021-07-01 at 12 13 02 PM](https://user-images.githubusercontent.com/1440943/124156493-b2b9b880-da65-11eb-8f7b-8b8e1a099223.png)

@PatrickA-RiseVision Thoughts?

Thanks!

**Comment by PatrickA-RiseVision** [comment]
Agreed, just add "fifth" to the list.

**Comment by ezequielc** [comment]
@jasoncaldwell @PatrickA-RiseVision Thanks, I will work on this in our next cooldown. Cheers!

**Comment by alex-deaconu** [comment]
The fix is pretty straight forward, however it will cause data inconsistencies. Adding a value for the `5th week` would cause all existing `Last week` values to become `5th week`. It also requires the same fixes in Viewer, rise-playlist, and Apps.

From BQ, there are 15 Legacy Presentations and 9 Schedules using the "Last Week" option.

Based on the fact that this functionality has been unchanged since Schedules/Presentations were first implemented, the very low usage and the fact that it is the first time we have had this request, my initial recommendation is that we leave this as is, as a known flaw.

If we do decide to pursue, in order to resolve the data inconsistency, my recommendation is we manually update the items to from `5th week` to `Last week`.

@PatrickA-RiseVision @ezequielc @alanclayton wondering let me know if you would agree to closing or you feel we should pursue? Thanks!

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision after speaking with Alan and Ezequiel, we were wondering if you could confirm if this was a User reported issue or something you stumbled upon yourself. Any feedback as to the impact of this defect so we can determine if we should pursue or not would be useful. Thanks!

**Comment by PatrickA-RiseVision** [comment]
@alex-deaconu Yes this is user-reported.  We haven't had more than 1 user report it.  He's currently working around it by manually scheduling dates.

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision sounds good, thanks for the update. We have a fix ready for release on Monday and we will be providing the Presentations/Schedules that need to be updated to Support. Thanks!

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision just a heads up, the fix for this has been deployed. Also, I've provided the list of content that needs to be updated in Slack. Closing. Thanks!
