### ISSUE TITLE
Presentation with no content in Placeholders created in Classic Editor can't be opened in new Editor

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#324]
<b>How it works now:</b> 
1. View <a href="https://rva.risevision.com/#/PRESENTATION_MANAGE/id=757e6f46-62f6-437b-9ab0-41bcc4d96cfa?cid=e8323047-adfb-4c6b-9562-35b6a3a9bec5">this Presentation</a> in the Classic Editor. Notice that there is no content in any Placeholder.
2. Try to open that same Presentation in the <a href="https://apps.risevision.com/editor/list?cid=e8323047-adfb-4c6b-9562-35b6a3a9bec5">new Editor</a>, notice that it will not open.

<b>This is the User's Presentation as an exact duplicate did not result in the same issue.</b>

If you right click and 'Open In New Tab' you land on the Home page in that new tab, which shows it's Editor that isn't reading properly.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 324 - Presentation created in Class Editor cannot be opened in new Editor.](https://trello.com/c/Vz7xIOvf/3138-issue-324-presentation-created-in-class-editor-cannot-be-opened-in-new-editor)

**Comment by alex-deaconu** [comment]
@robb-price is this related to https://community.risevision.com/rise_vision_inc/topics/presentation-editor-wont-open-6s4h1kstf2f3n?utm_source=notification&utm_medium=email&utm_campaign=new_topic&utm_content=topic_link ? Thanks!

**Comment by robb-price** [comment]
@alex-deaconu Yes.

**Comment by alex-deaconu** [comment]
@robb-price sounds good. Thanks!

**Comment by fjvallarino** [comment]
@robb-price the Community issue is caused by the user modifying a presentation (a non-empty, somehow complex, one) manually and leaving it in an invalid state (it was missing a '\' symbol, which caused a parsing error). There's no way of automatically fixing what the user breaks by tinkering, but we can validate the content before saving the presentation in order to avoid this type of error. 

Just to clarify, if something is broken in the old Editor and they try to open it in the new one, there's nothing we can do (unless, of course, we modify the old editor)

@alex-deaconu @ezequielc FYI

**Comment by ezequielc** [comment]
@fjvallarino @robb-price Given the discussion, should this be closed? Thanks

**Comment by robb-price** [comment]
@ezequielc I thought that this was going to be corrected in the new Editor? If that is the case, shouldn't this remain open until this is corrected?

**Comment by ezequielc** [comment]
@robb-price Makes sense. Thanks.

**Comment by RV-Adrian** [comment]
@robb-price Card looks complete but not sure given the conversation above. Please close if so, thanks!

**Comment by ezequielc** [comment]
@robb-price Given the discussion, we implemented a validation of the content before fixed. I consider this is closed. Please reopen if you think otherwise. Thanks!
