### ISSUE TITLE
When you delete a Presentation that is in a Schedule, it does not delete it from the Schedule.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#365]
<b>How it works now:</b>
1. Create a Presentation, add it to a Schedule.
2. Delete the Presentation. Notice that it is not deleted from the Schedule.

For further clarification: https://goo.gl/gbv3vS

<b>How it should work</b>
When you delete a Presentation, it should be deleted from the Schedule as well.

**Comment by alex-deaconu** [comment]
Sample Schedule: https://apps.risevision.com/schedules/details/bf8b8a52-bc90-48d8-b689-30a7b4dc255c?cid=094dae65-6c23-452f-90a4-46d1af5ceb12

**Comment by alex-deaconu** [comment]
@robb-price this issue has now been addressed. To confirm, instead of removing the Presentation from the Schedule(s) it's used in, we are presenting an Error message to the User informing them this Presentation is used elsewhere (https://screencast.com/t/O8H0UXGJZFT). This is similar to how the RVA behaves. Please validate and close if acceptable. Thanks!

**Comment by ezequielc** [comment]
@robb-price Are we good to close this? Thanks!
