### ISSUE TITLE
Schedules in Arizona Time change unintentionally when DST time changes.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#506]
<b>How it works now</b>
Using <a href="https://store.risevision.com/account?cid=097790dd-d1eb-470d-9f2e-012b7a926d12">this Company</a> as the example, they are in Arizona, which does not follow DST. Since Arizona does not use Daylight Saving Time,  they never change their clocks, and therefore cannot use the normal Mountain time zone selection. There should be an Arizona time zone option.

This is what happens with timeline scheduled content:
1. User sets times to 5a-5p and 5p-5a, and they work.
2. After DST starts, the Display begins showing content ahead by 1 hour (6 am - 6 pm, 6 pm - 6 am)
3. Schedules will have automatically changed to 6a and 6p.
4. No way to select the Arizona Time zone since it is not in the dropdown, so the only option is to change the times back to 5pm.

<b>How it should work</b>
Timelines should recognize the Arizona Time Zone which does not change when DST occurs.

**Comment by alex-deaconu** [comment]
@robb-price Timelines follow OS time. If the clock on the particular machine is not configured properly, or doesn't follow the timezone correctly, our Timeline option will just follow that. The timezone options in Apps are not used for Timeline content.

However, if that Timezone is indeed missing, we can update accordingly, but it won't make any difference.

Thanks.

**Comment by robb-price** [comment]
@alex-deaconu This user said that the times changed automatically in their Schedules, without them making any changes at all. 

Would the issue be that a user in a different time zone, possibly one that follows DST Time saved the Schedule with the incorrect time?

**Comment by alex-deaconu** [comment]
@robb-price to confirm, are you saying that originally the Timeline was defined at 5am-5pm, but now the Timeline definition says 6am-6pm (somehow was changed in the Apps UI)? Or are you saying that on the Display, the Presentation play from 6am-6pm, instead of 5am-5pm which is what is defined in the Timeline?

**Comment by alex-deaconu** [comment]
@robb-price I tried to replicate this in Apps and in the RVA using the Arizona timezone on my laptop, and the Colorado timezone. Both instances the time showed up correctly (5am-5pm). At this point I'm stuck on this, because I can't replicate, or I don't know how to replicate.

Can you find a way to do so? Thanks.

**Comment by robb-price** [comment]
@alex-deaconu I don't think there would be a way to get this to occur until the next DST. Since it was only one user who reported this issue, I think we can close this, and investigate the next time this issue occurs (when DST occurs again). This way we can see it in action.

**Comment by sshanky** [comment]
@alex-deaconu @robb-price I was just notified by my client that the schedule change occurred one hour early since DST. As a quick fix, I have gone to Company Settings and changed their company time zone to Pacific (labelled as "(GMT -08:00) Pacific Time (US & Canada], Tijuana", since they are now on GMT-7 (PDT), which is the same as Arizona, which remains locked to MST (mountain STANDARD time), because we do not use Daylight Saving here.

[Please note: Pacific is now GMT-7 (PDT), since they changed their clock; during the winter, when there's no daylight savings time, they have GMT-8 (PST)].

I understand this is a complex topic, but, in my humble opinion, this is something worth fixing. Not only is it very rare to encounter an application that omits Arizona (Phoenix, for example, is the Linux timezone name), but it's also worth remembering you have clients in Arizona, and all of them are going to have this problem if they decide to use any time-based scheduling. For now, we are forced to change time zones twice a year. There are other parts of the US and the world that do not observe DST. See: https://en.wikipedia.org/wiki/Daylight_saving_time_in_the_United_States

Here is a post that provides best practices for handling multiple time zones, in case it helps:
https://stackoverflow.com/a/2532962/1133387

I hope that helps. Thanks a lot for taking the time to read it.

**Comment by sshanky** [comment]
By the way, is it possible that the issue is related to the fact that the schedule is controlled by Rise Vision's server time, not the client's time? The content provided by the server to the player is determined by the schedule, which is served based on the server's understanding of the local time zone. Since there's no option to choose the correct local time zone for AZ (i.e. there's no way to choose a time zone that doesn't shift when DST starts and ends), the server acts incorrectly, as though times have changed where the client is located.

**Comment by robb-price** [comment]
Steve,

Can you confirm that the Timezone on the media players themselves are the correct timezone and are showing the correct time?

**Comment by sshanky** [comment]
Hi @robb-price and @alex-deaconu 

I checked on one of the media players (we're using Amazon Fire Sticks) and the time zone seems to be set to California, not Arizona. We are going to check the production units tomorrow when we will have access and find out if they are also set to California. California is currently PDT (which is the same as Arizona's MST), but we are still an hour off for some reason. I'll confirm tomorrow and find out, but I am probably going to have to eat my words and apologize for putting you through this if that's the problem. I will let you know. (However, I still maintain that there should be an Arizona-specific time zone, or at least an option to deactivate DST, to make the settings as precise as they should be.)
Thanks

**Comment by robb-price** [comment]
@sshanky No worries, as long as we get it figured out!

We look forward to hearing form you!

**Comment by sshanky** [comment]
Changing the time on the units did solve the problem. They were set to a california time zone by default, even though the Amazon account has an Arizona location set, and the devices were physically located in Arizona. Thanks again for all the support and sorry for consuming unnecessary time.
