### ISSUE TITLE
Safari and Firefox Quantum show Displays as offline even if they are not

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#579]
## What is the expected behavior?
When you look at your list of Displays on displays.risevision.com it should show the proper status instead of always showing as offline.

## What is the actual behavior?
All Displays show as offline regardless of the actual status

## What steps can be taken to replicate the problem?
Login to displays.risevision.com in Firefox or Safari and look at any list of Displays that should be showing as online.

In Chrome:
![image](https://user-images.githubusercontent.com/33877348/37221267-90b28670-2386-11e8-81e2-ecc831bc8867.png)

In Firefox Quantum:
![image](https://user-images.githubusercontent.com/33877348/37221215-657eb1e0-2386-11e8-994e-f965cfceb290.png)
![image](https://user-images.githubusercontent.com/33877348/37221338-ca212b00-2386-11e8-97a8-1fb112af54cb.png)

In Safari:
![image](https://user-images.githubusercontent.com/33877348/37221186-4b7f5150-2386-11e8-8cbb-9f70560680b8.png)
![image](https://user-images.githubusercontent.com/33877348/37221317-baac9376-2386-11e8-8461-7e281d449948.png)

**Comment by rudibravo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Safari and Firefox Quantum show Displays as offline even if they are not [2]](https://trello.com/c/OrHF7fCG/3261-safari-and-firefox-quantum-show-displays-as-offline-even-if-they-are-not-2)

**Comment by rudibravo** [comment]
@Rise-Vision/apps The apps is calling a new URL and Firefox/Safari is giving errors due to misconfigured CORS settings.

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://services.risevision.com/messaging/presence. (Reason: missing token ‘content-type’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

I tried as a quick fix to include the content-type on the http request [here](https://github.com/Rise-Vision/rise-vision-apps/blob/6c9078723c0812f036d466741895b7ce13796a6c/web/scripts/displays/services/svc-primus.js#L81) but it didn't help. What slows me down is that I can't replicate localhost, even pointing to production because the CORS is setup for risevision.com.

@tejohnso FYI, maybe you have a better idea here.

Thanks

**Comment by tejohnso** [comment]
@kaden-rise This should be okay now. Please confirm.
