### ISSUE TITLE
Corrupt Rise Cache Database is causing a Player to sit on File is Downloading

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#655]
Operating System Version: 64 Bit Ubuntu 14.04
Player Version: RisePlayerElectron 2018.05.16.13.56 Standard
Viewer Version: 2-01-201804171855
What is the expected behavior?
The Files should download as expected into the Cache.

What is the actual behavior?
Player is sitting on "File is Downloading" message, while the logs show this:
![image](https://user-images.githubusercontent.com/6862256/40737390-9980cf96-640e-11e8-9177-e50e88571135.png)

What steps can be taken to replicate the problem?
I've never seen this on another Display and so far can't replicate.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [Ticket blocked] Issue 723: Corrupt Rise Cache Database is causing a Player to sit on File is Downloading](https://trello.com/c/X0yauQ5m/8025-3-ticket-blocked-issue-723-corrupt-rise-cache-database-is-causing-a-player-to-sit-on-file-is-downloading)

**Comment by ezequielc** [comment]
@robb-price @alanclayton I assume this should go to Delivery, right? Thanks

**Comment by alanclayton** [comment]
@ezequielc Yes, should be delivery, but @robb-price I think this is a duplicate to https://github.com/Rise-Vision/rise-launcher-electron/issues/723. Which we are not pursuing because rc is being replaced with rise local storage. Image and Video are being updated to use rls now and should be shipping in the next couple of days. 

@stulees are you going to publish directions on how to set the flag so that support can manually update a display if necessary?

**Comment by stulees** [comment]
@alanclayton Yes I can do that. At the moment it can only be done for widgets configured for single file. Folder is still a work in progress. 

@alanclayton @robb-price Where would be best to publish these instructions?

**Comment by robb-price** [comment]
@alanclayton Yes it was here created at @tejohnso 's request. @stulees If you want to post those instructions here, we can use them if/when we run into this issue again.
