### ISSUE TITLE
RVA: Web Page widget doesn't appear in the Widget list when adding content

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#742]
### What is the expected behavior?
Web Page widget appears in the list of widgets when adding content in RVA.

### What is the actual behavior?
Web Page widget is missing from the list of widgets when adding content in RVA.

### What steps can be taken to replicate the problem?
1. Open rva.risevision.com and log in
2. Open a presentation and create a placeholder if you do not already have one.
3. Right-click into your placeholder and click Properties
4. In the Playlist, click on "Add" and choose "Content" out of the context menu.
5. Search for Web Page widget.  It does not appear in the list of widgets.

**Comment by ezequielc** [comment]
@PatrickA-RiseVision This issue is a result of the latest pricing changes.
We talked about it and the conclusion is that we are not going to keep RVA up-to-date as it is being deprecated. 
I updated the [announcement](https://help.risevision.com/hc/en-us/community/posts/360011541143-Classic-Editor-rva-risevision-com-End-of-life) to state this decision. Thanks
