### ISSUE TITLE
Customer purchased a plan, but account showing as free

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/rise-vision-apps#745]
### What is the expected behavior?
As a user, when I have purchased a plan, I should see this plan in the status bar, and I should have the ability to toggle and turn on the Display License for a Display.

### What is the actual behavior
The user does not see the purchased plan in the status bar, nor do they have access to the licensed displays.  If the user selects "See Our Plans" in the status bar, their Plan is shown as Free. 
 Furthermore, when they attempt to go to the Account & Billing link in the menu, the Plan Window appears.

### What steps can be taken to replicate the problem?
https://apps.risevision.com/?cid=89d5e521-c80e-487d-be3c-dabe938493ff

To replicate the problem, you can select the "See our Plans" or "Account & Billing" link.

**Comment by ezequielc** [comment]
@jrkuchta This issue is related to the previous issue we just fixed. 
This company had a Basic Trial that was not cancelled automatically when they subscribed to the Advanced Plan.
We manually cancelled the trial after that, so the most recent state in our system was that they had a cancelled Basic Trial.
To fix incorrect states, we need to follow this article informing the correct subscription id: https://help.risevision.com/hc/en-us/articles/360000384883-Incorrect-subscription-on-Plans-Bar

I already did it with their Advanced Plan, so this is fixed for the user.
Thanks!
