### ISSUE TITLE
New Store doesn't behave like Old Store when a CC Declines

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#777]
### What is the expected behavior?
When a credit card declines, an invoice exists on the user account.  Users can self-serve to view invoices, correct payment, and pay directly from the invoice.  If a change to the invoice is required (i.e. tax exempt), we can regenerate the invoice so they can continue to self serve.

### What is the actual behavior?
When a credit card declines, an invoice exists on the user account in Chargebee.  If a change to the invoice is required, it's impossible to generate a new invoice if the credit card is still declining.  Manual intervention is required once the user has updated their payment method, which creates a support touch.

### What steps can be taken to replicate the problem?
1. Create a subscription in an account in Chargebee
2. Have the subscription be billed automatically to a credit card that is declined.
3. Void the invoice, as though you were making a change.
4. Attempt to re-generate the invoice in Chargebee.
5. The CC declines; an invoice cannot be generated and the amount will remain unbilled.

**Comment by jrkuchta** [comment]
@brianloosbrock Can you take a look at this and let me know your thoughts?  This is not a process I am entirely familiar with and would like your input.

**Comment by jrkuchta** [comment]
@ezequielc @PatrickA-RiseVision I agree, I think this is a change in process rather than a bug.  If I am understanding the situation correctly, I would suggest changing the "auto-collection" to Off on the subscription prior to  regenerating the invoice.   It will allow you to regenerate the invoice and then you can turn the auto-collection back on.  Let me know if I am not understanding correctly, or if this process does not work.  Thanks!

**Comment by PatrickA-RiseVision** [comment]
@jrkuchta works for me, I'll queue a card. @btfrise fyi
