### ISSUE TITLE
As a Customer, I can't tell Paid and Unpaid invoices apart in My Account without downloading each invoice

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#799]
### What is the expected behavior?
As a customer, I can view My Account in the Rise Vision app and use the Billing History to determine which invoices have or have not been paid.

### What is the actual behavior?
As a customer, I can view My Account in the Rise Vision app and use the Billing History to view which invoices I have received, but I cannot determine whether they have been paid without downloading them individually as PDFs.

### What steps can be taken to replicate the problem?
View the billing history for any account.  There's no way to tell them apart without downloading the PDFs.

![image](https://user-images.githubusercontent.com/40774237/51188431-4f973400-18b4-11e9-82e0-9245f95ec629.png)

![image](https://user-images.githubusercontent.com/40774237/51188471-6a69a880-18b4-11e9-8dd5-2d013fc868aa.png)

**Comment by olegrise** [comment]
@PatrickA-RiseVision @ezequielc @alex-deaconu I submitted a ticket to Chargebee. Thanks.

**Comment by olegrise** [comment]
Here is the reply from Chargebee support "At the moment there is no option to display the status of invoice in the Customer Portal, however, I do understand the importance of this feature. That's why I have taken it up as a feature request for possible development in the future."

Considering their reply I'm not sure it makes sense to keep this ticket open. Any suggestions?

@PatrickA-RiseVision @ezequielc @alex-deaconu

**Comment by olegrise** [comment]
@alex-deaconu interesting idea. I checked the [API](https://www.chargebee.com/checkout-portal-docs/api.html#chargebee-portal-instance-object) - it doesn't look like it's possible.

**Comment by olegrise** [comment]
@PatrickA-RiseVision I'm going to close this issue. Chargebee added this use case to their feature request. We don't have any control over when they are going to implement it, so I don't think it makes sense to keep this issue open. If this issue causes too many touches for support, then we can take a look at alternatives. One of the options is to display invoices directly on the Account & Billing page instead of opening Chargebee's Portal modal.
