### ISSUE TITLE
Files with &amp; in the name cause an error message

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-vision-apps#808]
*Expected Behavior*
When saving a presentation, the editor should respect special character sequences such as `&amp;` in file names selected from widgets.

*Actual Behavior*
After clicking Save, all occurrences of `&amp;` are changed to `&`; this results in the file not being found by a widget running in preview or the display.

This was previously reported as a widget-image issue here: https://github.com/Rise-Vision/widget-image/issues/193
Further details and sample presentation here: https://trello.com/c/4Iw9aUBQ/6296-widget-image-issue-193-3

*Steps to reproduce*

- Create a local image with a name like `photo&amp;monster.jpg`
- Create a new presentation.
- Add a placeholder and an image widget.
- Upload the local image with the name.
- Check the presentation source code, all item name, storage name and file name will properly reference `photo&amp;monster.jpg`
- Click Save.
- Check the presentation source code again, now all item name, storage name and file name have been changed to `photo&monster.jpg`
- As a result, Preview won't show the image.
- If the image is selected again from storage, all item name, storage name and file name will have the correct name again, but the issue will reappear as soon as the Save button is clicked again.

Another related test, outside of the widget:
- Add a comment like `<!-- &amp; -->` just before `</html>` close tag:
- Click Save
- The comment will new be changed to `<!-- & -->`

The same will happen if the `&amp;` string is inserted into the generated warning comment before the presentationData variable assignment.

FYI @sheadarlison @stulees

**Comment by alex-deaconu** [comment]
To conclude on this issue:

From the original investigation, the Widget is sending the correct response, and we are also sending the correct response to the server. However, the issue occurs when the Google API call occurs. Something within the `gapi` code converts `&amp;` to `&` before it reaches the server.

My attempted fix for this issue was replacing `&amp;` with a unicode character string, and replacing it back when parsing. However this breaks the Viewer and the Widget no longer shows. We could update Viewer to parse in this manner as well, however my main concern is this inconsistency could cause issues elsewhere, with other Content in the Presentation or other Widgets.

This is an edge case and it is not worth the risk of breaking user Presentations. Also, Viewer is being deprecated.

Closing Issue. Thanks!
