### ISSUE TITLE
Editor does not load image in placeholder

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/rise-vision-apps#866]
### What is the expected behavior?
When using the image widget while in the editor, you can see a small preview/thumbnail in the placeholder of the image

### What is the actual behavior?
The image does not load until you either move the placeholder  or preview the image.

### What steps can be taken to replicate the problem?
1. add an image widget to presentation
2. Image won't load
3. drag placeholder, image will load

Created video of the error here:
https://goo.gl/ECbpkY

**Comment by ezequielc** [comment]
@tylermwight We can't replicate the issue. Could you clear cache and try again or from incognito and let us know if it still happens? Thanks!

**Comment by tylermwight** [comment]
@ezequielc 

I updated google chrome, cleared cache, and used incognito and I am still seeing the issue. Video here:
https://goo.gl/99YgJQ

Not sure what could be causing it

**Comment by ezequielc** [comment]
@tylermwight Thanks! Does it happen with all Presentations or this one in particular? Can someone else in Support replicate it as well? Thanks!

**Comment by ezequielc** [comment]
@tylermwight We still can't replicate this. Do you know if anyone else is having the issue? Also, could you share your browser version and a link to that Presentation from the video? Thanks
@btfrise fyi

**Comment by tylermwight** [comment]
@ezequielc Apologies for the delay. Yes I do have one user with this issue in ticket #33368

Previously I tested this on on chrome 72. I tested this with Kaden and he can reproduce the issue on his end. He reproduced on 72.0.3626.121. We both updated our Google Chrome to version "73.0.3683.86" and tested again. Kaden and I can still reproduce on the newest version of chrome.  This presentation is where we are replicating this:

https://apps.risevision.com/editor/workspace/abf458ad-9ef0-4216-8720-fe98cbf2319d/?cid=40920f96-9621-4cce-a46e-1b839e5c5688

I tested with Colby though, and he cannot replicate this error on the same presentation, so I'm not sure what the difference could. Colby is currently running 72.0.3626.121 

Here is a video where I checked the network tab as well: https://goo.gl/4SDd5u

**Comment by ezequielc** [comment]
Thanks @tylermwight, we will continue our investigation.

**Comment by ezequielc** [comment]
@Rise-Vision/content I want to get your feedback if this issue should go to Content.

Just to give some context, this issue is not easily replicable. I couldn't replicate it on my machine but I manage to replicate on a Windows 10 VM. 

Basically, it looks like a browser rendering issue. The widget iframe is properly loaded, all widget events are fired, but the widget is not rendered by the browser. If I interact with the iframe, like moving it, or even by clicking on browser Inspect, the widget reappears. 

I managed to circumvent the issue by forcing refresh in Apps (PR https://github.com/Rise-Vision/rise-vision-apps/pull/878), but I don't think it is a good solution.

Also, when I use a staged (older?) version of the Image widget, the issue doesn't happen. That is why I am bringing this to you, so you can take a look if there were any changes to the widget that could cause the issue.

Sample Presentation with production image widget (left) and staging (right): https://apps-stage-1.risevision.com/editor/workspace/981672ef-3b0b-4294-bd58-d1383df28132/?cid=6df71cf2-80af-40b8-bdb4-9da93b838677 

Thanks!
@Rise-Vision/apps fyi

**Comment by stulees** [comment]
@ezequielc I've recreated in my Win 10 VB also, in fact it appears it can be reliably recreated there, which my Win 10 VB is using Chrome 73.0.3683.86 (Official Build)(32-bit). The staged widget you configured on the right is a year old. There are a multitude of changes that have been deployed since then, too many to decipher what _may_ be contributing to this quirk (i.e. the widget was refactored to use RLS instead of Rise Cache).

I'm not convinced though this is best suited for Content to take. The widget is not showing any kind of similar behaviour in Player or Preview and it is not logging any error. This Windows quirk appears to be isolated to Editor.

**Comment by alex-deaconu** [comment]
@stulees thanks for confirming. @ezequielc I will review your pending PR and if we don't have any better options we can release.

@alanclayton FYI the above, you wanted to be kept in the loop on this issue.

Thanks!

**Comment by alanclayton** [comment]
👍

**Comment by ezequielc** [comment]
@alex-deaconu @stulees Thanks!

**Comment by ezequielc** [comment]
@tylermwight A fix for the issue has been released. Let me know if you still have problems. Thanks!
