### ISSUE TITLE
Template Editor: Licensing - Expired/Cancelled Modal UI Text Centering

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-vision-apps#943]
Problem: The error message does not appear to be vertically centered in the box.

Solution: Reduce padding between "x" and "your rise vision plan is no longer active"? Similar to this zpl.io/2yOX1eJ Specifically, I would try reducing what appears to be 20px padding between those elements to 5px. In the end, we just want it to look visually centered in the box.

**Comment by ezequielc** [comment]
@mmeiers This issue was fixed by https://github.com/Rise-Vision/rise-vision-apps/pull/1036. 
We updated the modal to use the new Style Guide:
<img width="547" alt="Screen Shot 2019-06-18 at 3 17 03 PM" src="https://user-images.githubusercontent.com/7738553/59708976-33d5e800-91dc-11e9-9cbf-55599d633525.png">
Thanks!
