### ISSUE TITLE
Removing Display from Schedule does not always work.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#947]
###How to recreate
1. This defect cannot be replicated every time.
2. Remove a Display from a Schedule.
3. Confirm that the number of Displays assigned to that Schedule has reduced by one.
4. Save Schedule.
5. Go to another Schedule.
6. Assign the Display that you just removed to this new Schedule.

###What happens.
See error message **Failed to update Schedules** The Schedule could not be updated. Another Schedule "xxx xxx xxx" is set to be distributed to the same Displays.

The Display hasn't actually been removed from the original Schedule.

###What should happen.
When a Display is removed from a Schedule, it should always be removed, and we should be able to add it to another Schedule immediately.

###Example
While I have not been able to recreate myself, you can see an example of the defect in action in [this fullstory session](https://fsty.io/v/89qVvtm).

**Comment by ezequielc** [comment]
@btfrise After spending some time investigating the issue, I could not replicate it or clearly identify what could have caused it.
As seen in FullStory, the user had 4 displays in distribution and changed to 3.
But the server logs for updating the schedule still show it being distributed to the original 4 displays, instead of 3. So it looks like an issue on client side. I tried multiple scenarios but could not replicate it. Talking with Shea and Alan, we decided to close the issue for now. Thanks!
