### ISSUE TITLE
Can't sign up in Safari 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#995]
Video: https://drive.google.com/file/d/1W1dP-uqdn-cjOvXJwSKjtZRolAfQvXzK/view?usp=sharing

**Comment by ezequielc** [comment]
@sheadarlison This happens because 3rd-party cookies are disabled. As you can see in the video, there is a warning at the top of the screen about that. Thanks

**Comment by sheadarlison** [comment]
@ezequielc this issue was reported by Scott but I had my girlfriend try this on her Mac and she doesn't have cookies blocked and the same issue happened. 

Can you please try on your mac and see if you can recreate?

**Comment by ezequielc** [comment]
@sheadarlison I tested and I could not replicate it. I tried with single and multiple google accounts and both worked for me. Thanks

**Comment by sheadarlison** [comment]
@ezequielc in safari could we update the message to say: 

Cookies Are Disabled. Rise Vision needs to use cookies to properly function. Please enable cookies and cross-site tracking on your web browser and refresh this page. 

I think this issue can be the lowest priority as it affects a small number of users.

**Comment by alex-deaconu** [comment]
@sheadarlison @ezequielc I took a look at this issue. Similar to what Ezequiel found, I was not able to replicate it in Safari. The main issue is, I cannot replicate even with the "Prevent cross-site tracking" option checked (which is basically disabling 3rd party cookies).

Based on this, our notification for 3rd party cookies may be incorrect (Yes, our app completely breaks if all cookies are disabled but I think so does the rest of the internet). Theoretically, the 3rd party cookies were only used for cross-login from Apps to Store to RVA, which indeed doesn't work once that option is disabled. However, we no longer have apps on different domains. So, my first suggestion is to re-evaluate that 3rd party cookie check and whether we need it at all.

Second, there may be an unrelated issue in Safari which we need to identify and fix. It could be caused by a plugin or something else. I'm still looking into that.

Thanks.

**Comment by sheadarlison** [comment]
@alex-deaconu [Given these #s](https://docs.google.com/document/d/1xzhbczhRdYPqa_AgNronChZgS2cN1iSnT4m6Yg-WvI0/edit?usp=sharing) I think we should spend the time fixing this problem. Your plan of action makes sense to me but I'd like Alan to review as well. 

@alanclayton can you chime in here? 

Thanks

**Comment by alex-deaconu** [comment]
@sheadarlison I got some additional info from @alanclayton (he was able to replicate), so I have something to work off here. Will continue to investigate this. Thanks.

**Comment by alex-deaconu** [comment]
@sheadarlison @alanclayton this issue should now be resolved with the latest release. To confirm, the fix should improve the handling of the Google Authentication result in Apps for all browsers (and resolve the Safari issue specifically). Thanks!
